FROM node:20-bookworm

RUN apt-get update
RUN apt-get install -y python3

WORKDIR /app

COPY client/package.json ./
RUN npm install --legacy-peer-deps

# COPY client/ .

EXPOSE 3000

# CMD ["npm", "start"]