services:
  # backend:
  #   build:
  #     context: ../
  #     dockerfile: infra/docker/backend/Dockerfile
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ../server:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - DB_USER=${DB_USER}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_HOST=${DB_HOST}
  #     - DB_PORT=${DB_PORT}
  #     - DB_DATABASE=${DB_DATABASE}
  #     - PORT=5000
  #     - STRIPE_KEY=${STRIPE_KEY}
  #     - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
  #     - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
  #     - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
  #     - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
  #   depends_on:
  #     - db
  #   networks:
  #     - app-network

  # frontend:
  #   build:
  #     context: ../
  #     dockerfile: infra/docker/frontend/Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - ../server/client:/app
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network

  db:
    build:
      context: ../
      dockerfile: infra/docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecom
    ports:
      - "5433:5432"
    volumes:
      - ../infra/volumes/postgres:/var/lib/postgresql/data
    networks:
      - ecom


networks:
  ecom:
    driver: bridge