services:
  ecom-db:
    build:
      context: ../
      dockerfile: infra/docker/postgres/Dockerfile.dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecom
    ports:
      - "5433:5432"
    volumes:
      - ../infra/volumes/postgres:/var/lib/postgresql/data
    networks:
      - ecom

  ecom-backend:
    build:
      context: ../
      dockerfile: infra/docker/backend/Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ../server:/app
      - /app/node_modules
    command: npm run start
    # depends_on:
    #   - ecom-db
    networks:
      - ecom

  ecom-frontend:
    build:
      context: ../
      dockerfile: infra/docker/frontend/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - type: bind
        source: "../client/craco.config.js"
        target: "/app/craco.config.js"

      - type: bind
        source: "../client/tailwind.config.js"
        target: "/app/tailwind.config.js"

      - type: bind
        source: "../client/src"
        target: "/app/src"

      - type: bind
        source: "../client/public"
        target: "/app/public"
    command: npm run start
    depends_on:
      - ecom-backend
    networks:
      - ecom


networks:
  ecom:
    driver: bridge