services:
  frontend:
    build:
      context: ../
      dockerfile: infra/docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - type: bind
        source: "../server/client/craco.config.js"
        target: "/app/craco.config.js"

      - type: bind
        source: "../server/client/tailwind.config.js"
        target: "/app/tailwind.config.js"

      - type: bind
        source: "../server/client/src"
        target: "/app/src"

      - type: bind
        source: "../server/client/public"
        target: "/app/public"
    # depends_on:
    #   - backend
    command: npm run start
    networks:
      - ecom

networks:
  ecom:
    driver: bridge